spring:
  application:
    name: cmapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmapi
    username: root
    password: 123456
  mvc:
    pathmatch:
      # 指定URL路径匹配的策略--Ant--风格，默认的URL路径匹配的策略是AntPathMatcher
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    # 存储类型
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
    password: 123321
server:
  port: 7529
  # 将Servlet的上下文路径配置为“/api”，那么应用的根路径就变成了“http://localhost:7529/api/”。
  servlet:
    context-path: /api
mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
#    # 打开驼峰映射
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
chenmeng:
  api:
    client:
      access-key: 沉梦
      secret-key: abc
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

