server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, chenmeng
      routes:
        - id: api_route
          # 设置转发到哪个网址
          uri: http://localhost:8123
          # 前缀断言
          predicates:
            - Path=/api/**
# 输出 trace 级别日志，看网关信息
logging:
  level:
    org:
      springframework:
        gateway: trace